export const Types = {
    GET_ALL_PRODUCT_REQUEST: 'GET_ALL_PRODUCT_REQUEST',
    GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',

    //Scroll down event type
    SCROLL_DOWN: 'SCROLL_DOWN',
    SCROLL_UP: 'SCROLL_UP'
}