export const Types = {

    //Product
    GET_ALL_PRODUCT_REQUEST: 'GET_ALL_PRODUCT_REQUEST',
    GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
    ADD_FAVORITE_ITEM_REQUEST: 'ADD_FAVORITE_ITEM_REQUEST',
    ADD_FAVORITE_ITEM_SUCCESS: 'ADD_FAVORITE_ITEM_SUCCESS',
    REMOVE_FAVORITE_ITEM_REQUEST: 'REMOVE_FAVORITE_ITEM_REQUEST',
    REMOVE_FAVORITE_ITEM_SUCCESS: 'REMOVE_FAVORITE_ITEM_SUCCESS',
    GET_FAVORITE_ITEMS_REQUEST: 'GET_FAVORITE_ITEMS_REQUEST',
    GET_FAVORITE_ITEMS_SUCCESS: 'GET_FAVORITE_ITEMS_SUCCESS',

    //Scroll down event type
    SCROLL_DOWN: 'SCROLL_DOWN',
    SCROLL_UP: 'SCROLL_UP',
    HIDE_TAB_BAR: 'HIDE_TAB_BAR',
    UN_HIDE_TAB_BAR: 'UN_HIDE_TAB_BAR',

    //User authenticate
    GET_USER_INFO_REQUEST: 'GET_USER_INFO_REQUEST',
    GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOG_OUT_REQUEST: 'LOG_OUT_REQUEST',
    LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
    STORE_USER_TEMP_REQUREST: 'STORE_USER_TEMP_REQUREST',
    STORE_USER_TEMP_SUCCESS: 'STORE_USER_TEMP_SUCCESS',
    SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
    SIGN_UP_FAILED: 'SIGN_UP_FAILED',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',

    //Body tab profile screen
    TAB_TO_FAVORITE: 'TAB_TO_FAVORITE',
    TAB_TO_TRACKING_ORDER: 'TAB_TO_TRACKING_ORDER',

    //Cart type
    ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    REMOVE_CART_ITEM_REQUEST: 'REMOVE_CART_ITEM_REQUEST',
    REMOVE_CART_ITEM_SUCCESS: 'REMOVE_CART_ITEM_SUCCESS',
    GET_CART_REQUEST: 'GET_CART_REQUEST',
    GET_CART_SUCCESS: 'GET_CART_SUCCESS',
    UPDATE_PRODUCT_QUANTITY_REQUEST: 'UPDATE_PRODUCT_QUANTITY_REQUEST',
    UPDATE_PRODUCT_QUANTITY_SUCCESS: 'UPDATE_PRODUCT_QUANTITY_SUCCESS',

    //Order
    CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST',
    CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
    PUSH_cREATE_ORDER_REQUEST: 'PUSH_cREATE_ORDER_REQUEST',
    PUSH_CREATE_ORDER_SUCCESS: 'PUSH_CREATE_ORDER_SUCCESS',
    MODAL_SUCCESS_VISIBLE: 'MODAL_SUCCESS_VISIBLE',
    MODAL_SUCCESS_INVISIBLE: 'MODAL_SUCCESS_INVISIBLE',

    TRACKING_ORDER_REQUEST: 'TRACKING_ORDER_REQUEST',
    TRACKING_ORDER_SUCCESS: 'TRACKING_ORDER_SUCCESS'

}