export const Types = {

    //Product
    GET_ALL_PRODUCT_REQUEST: 'GET_ALL_PRODUCT_REQUEST',
    GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
    ADD_FAVORITE_ITEM: 'ADD_FAVORITE_ITEM',
    REMOVE_FAVORITE_ITEM: 'REMOVE_FAVORITE_ITEM',

    //Scroll down event type
    SCROLL_DOWN: 'SCROLL_DOWN',
    SCROLL_UP: 'SCROLL_UP'
}